class _BotCommands:
    def __init__(self):
        self.StartCommand = 'start'
        self.MirrorCommand = 'mirror'
        self.UnzipMirrorCommand = 'unzip'
        self.TarMirrorCommand = 'tarul'
        self.CancelMirror = 'cancel'
        self.CancelAllCommand = 'cancelall'
        self.ListCommand = 'search'
        self.StatusCommand = 'status'
        self.AuthorizedUsersCommand = 'users'
        self.AuthorizeCommand = 'authorize'
        self.UnAuthorizeCommand = 'unauthorize'
        self.AddSudoCommand = 'addsudo'
        self.RmSudoCommand = 'rmsudo'
        self.PingCommand = 'ping'
        self.RestartCommand = 'restart'
        self.StatsCommand = 'statics'
        self.HelpCommand = 'help'
        self.LogCommand = 'log'
        self.SpeedCommand = 'speedtest'
        self.CloneCommand = 'copy'
        self.CountCommand = 'count'
        self.WatchCommand = 'ytdl'
        self.TarWatchCommand = 'tarytdl'
        self.DeleteCommand = 'delete'
        self.UsageCommand = 'dyno'
        self.MediaInfoCommand = 'mediainfo'
        self.ConfigMenuCommand = 'config'
        self.ShellCommand = 'shell'
        self.UpdateCommand = 'update'
        self.ExecHelpCommand = 'exechelp'
        self.TsHelpCommand = 'tshelp'

BotCommands = _BotCommands()
